export const BASE_URL = 'http://localhost:5000';
export const DASHBOARD_LIST_PER_PAGE = 5;
export const LIST_BOOKS_PER_PAGE = 6;
export const LIST_AUTHORS_PER_PAGE = 6;
export const LIST_GENRES_PER_PAGE = 6;
export const LIST_PER_PAGE = 5;
export const GENRES_SIDEBAR_LIMIT = 10;
export const GENRES_HOME_LIMIT = 8;
export const BOOKS_HOME_LIMIT = 6;
export const AUTHORS_HOME_LIMIT = 6;
export const FONT=[
    'Nunito',
    '-apple-system',
    'BlinkMacSystemFont',
    '"Segoe UI"',
    'Roboto',
    '"Helvetica Neue"',
    'Arial',
    'sans-serif',
    '"Apple Color Emoji"',
    '"Segoe UI Emoji"',
    '"Segoe UI Symbol"',
].join(',');
export const ERROR_SET = 'ERROR_SET';
export const ERROR_REMOVE = 'ERROR_REMOVE';

export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_REQUEST = 'FETCH_AUTH_REQUEST';
export const FETCH_AUTH_FAILURE = 'FETCH_AUTH_FAILURE';

export const FETCH_AUTHORS_REQUEST = 'FETCH_AUTHORS_REQUEST';
export const FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAILURE';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';

export const FETCH_AUTHOR_REQUEST = 'FETCH_AUTHOR_REQUEST';
export const FETCH_AUTHOR_FAILURE = 'FETCH_AUTHOR_FAILURE';
export const FETCH_AUTHOR_SUCCESS = 'FETCH_AUTHOR_SUCCESS';

export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';

export const FETCH_GENRE_REQUEST = 'FETCH_GENRE_REQUEST';
export const FETCH_GENRE_FAILURE = 'FETCH_GENRE_FAILURE';
export const FETCH_GENRE_SUCCESS = 'FETCH_GENRE_SUCCESS';

export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';

export const FETCH_BOOK_REQUEST = 'FETCH_BOOK_REQUEST';
export const FETCH_BOOK_FAILURE = 'FETCH_BOOK_FAILURE';
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
